[project]
name = "quantumfetcher"
version = "1.1.1"
description = "Tool for fetching Quantum Break live action episodes for offline in-game playback"
authors = [
    {name = "Marek Grzyb",email = "marek@grzyb.dev"}
]
readme = "README.md"
license = "GPL-3.0-or-later"
license-files = [
    "LICENSE.md",
]
requires-python = ">=3.10"
dependencies = [
    "humanize>=4.16.0",
    "inquirer>=3.4.1",
    "requests>=2.34.2",
    "typer>=0.27.0",
    "yt-dlp>=2026.7.4",
]

[tool.uv]
package = true

[project.scripts]
quantumfetcher = "quantumfetcher:app"
