name: Debug Build

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            osname: Linux
          - os: windows-latest
            osname: Windows

    name: Build for ${{ matrix.osname }}
    permissions: write-all
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.14

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Build package
        run: poetry build

      - name: Install PyInstaller
        run: poetry run pip install pyinstaller
     
      - name: Build executable
        run: poetry run pyinstaller --copy-metadata readchar -F --name QuantumFetcher_${{ matrix.osname }} ./src/quantumfetcher/__init__.py
    
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Release_${{ matrix.osname }}
          path: dist
